### ISSUE TITLE
Recover from missing source file

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/sonar-kt-advance#1]
Projects may have an unusual build or synthesis of source files such that a obvious `*.c` is not available when running the scanner.  Currently the plugin will catch the missing file problem, yield an error, and stop.  Example attached.  Can the plugin recover and continue scanning in this situation?  

![screen shot 2016-12-20 at 9 35 00 am](https://cloud.githubusercontent.com/assets/1465947/21356986/39d29a34-c699-11e6-8892-5e98288456eb.png)

**Comment by compartia** [comment]
yes, reproduced.

**Comment by compartia** [comment]
to update in-Docker composites, use `docker-compose up --force-recreate`
